#ifndef _IMP_MAX_CHUNKS_H
#define _IMP_MAX_CHUNKS_H

#include <glib.h>

#include "imp_max_callbacks.h"

typedef struct {
	guint16 id;
	char *desc;
	MaxCallback callback;
} MaxChunk;

static MaxChunk max_cnt_chunks[] = {
	{ 0x0000, "container",                               NULL },
	{ 0x0001, "container",                               NULL },
	{ 0x0002, "container",                               NULL },
	{ 0x0003, "texture map container?",                  NULL },
	{ 0x0004, "container",                               NULL },
	{ 0x0005, "container",                               NULL },
	{ 0x0006, "container",                               NULL },
	{ 0x0007, "container",                               NULL },
	{ 0x0008, "container",                               NULL },
	{ 0x0009, "container",                               NULL },
	{ 0x000A, "container",                               NULL },
	{ 0x000B, "container",                               NULL },
	{ 0x000C, "container",                               NULL },
	{ 0x000D, "container",                               NULL },
	{ 0x000E, "container",                               NULL },
	{ 0x000F, "container",                               NULL },
	{ 0x0010, "container",                               NULL },
	{ 0x0011, "container",                               NULL },
	{ 0x0012, "container",                               NULL },
	{ 0x0013, "container",                               NULL },
	{ 0x0014, "container",                               NULL },
	{ 0x0015, "container",                               NULL },
	{ 0x0016, "container",                               NULL },
	{ 0x0017, "container",                               NULL },
	{ 0x0018, "container",                               NULL },
	{ 0x0019, "container",                               NULL },
	{ 0x001A, "container",                               NULL },
	{ 0x001B, "container",                               NULL },
	{ 0x001C, "container",                               NULL },
	{ 0x001D, "container",                               NULL },
	{ 0x001E, "container",                               NULL },
	{ 0x001F, "container",                               NULL },
	{ 0x0020, "container",                               NULL },
	{ 0x0021, "container",                               NULL },
	{ 0x0023, "container",                               NULL },
	{ 0x0110, "container",                               NULL },
	{ 0x0130, "container",                               NULL },
	{ 0x03F2, "container",                               NULL },
	{ 0x08FE, "container",                               NULL },
	{ 0x0901, "container",                               NULL },
	{ 0x092C, "container",                               NULL },
	{ 0x092D, "container",                               NULL },
	{ 0x092E, "container",                               NULL },
	{ 0x0AD2, "container",                               NULL },
	{ 0x0ADC, "container",                               NULL },
	{ 0x0AF0, "container",                               NULL },
	{ 0x0B0E, "container",                               NULL },
	{ 0x0B22, "container",                               NULL },
	{ 0x1000, "container",                               NULL },
	{ 0x1010, "container",                               NULL },
	{ 0x1020, "container",                               NULL },
	{ 0x1030, "container",                               NULL },
	{ 0x1040, "container",                               NULL },
	{ 0x1050, "container",                               NULL },
	{ 0x1060, "container",                               NULL },
	{ 0x1070, "container",                               NULL },
	{ 0x1080, "container",                               NULL },
	{ 0x1090, "container",                               NULL },
	{ 0x2000, "container",                               NULL },
	{ 0x2001, "container",                               NULL },
	{ 0x2004, "root node",                               NULL },
	{ 0x2006, "container",                               NULL },
	{ 0x2008, "container",                               NULL },
	{ 0x200A, "root node",                               NULL },
	{ 0x200B, "root node",                               NULL },
	{ 0x2010, "container",                               NULL },
	{ 0x2020, "container",                               NULL },
	{ 0x2030, "container",                               NULL },
	{ 0x2032, "container",                               NULL },
	{ 0x2038, "container",                               NULL },
	{ 0x2040, "container",                               NULL },
	{ 0x2050, "container",                               NULL },
	{ 0x2070, "container",                               NULL },
	{ 0x20A0, "container",                               NULL },
	{ 0x20B0, "container",                               NULL },
	{ 0x20C8, "container",                               NULL },
	{ 0x20F0, "container",                               NULL },
	{ 0x2100, "container",                               NULL },
	{ 0x2110, "container",                               NULL },
	{ 0x2120, "container",                               NULL },
	{ 0x2140, "container",                               NULL },
	{ 0x2150, "container",                               NULL },
	{ 0x21A0, "container",                               NULL },
	{ 0x21B0, "container",                               NULL },
	{ 0x2500, "container",                               NULL },
	{ 0x2512, "container",                               NULL },
	{ 0x2750, "container",                               NULL },
	{ 0x2755, "container",                               NULL },
	{ 0x2765, "container",                               NULL },
	{ 0x2800, "container",                               NULL },
	{ 0x39BF, "container",                               NULL },
	{ 0x4000, "material group",                          NULL },
	{ 0x5010, "container",                               NULL },
	{ 0x5020, "container",                               NULL },
	{ 0x5431, "container",                               NULL },
	{ 0x5600, "container",                               NULL },
	{ 0x7FC2, "container",                               NULL },
	{ 0xFFFF, NULL, NULL }
};

static MaxChunk max_chunks[] = {
	{ 0x0001, "binary (i32)",                            NULL },
	{ 0x0002, "binary (i32)",                            NULL },
	{ 0x0003, "binary (i32)",                            NULL },
	{ 0x0004, "binary (0+)",                             NULL },
	{ 0x0005, "string list",                             max_cb_0x0005 },
	{ 0x0009, "binary (16)",                             NULL },
	{ 0x000A, "binary (15)",                             NULL },
	{ 0x000B, "binary",                                  NULL },
	{ 0x000C, "binary (i16)",                            NULL },
	{ 0x0100, "text",                                    max_cb_0x0100 },
	{ 0x1201, "binary",                                  NULL },
	{ 0x1230, "file name",                               max_cb_0x0100 },
	{ 0x1240, "file type",                               max_cb_0x0100 },
	{ 0x2034, "binary (i32xn)",                          NULL },
	{ 0x2037, "file name",                               max_cb_0x0100 },
	{ 0x2039, "description",                             NULL },
	{ 0x2042, "name",                                    NULL },
	{ 0x2060, "binary (i32x4)",                          NULL },
	{ 0x4001, "material name",                           max_cb_0x0100 },
	{ 0xFFFF, NULL, NULL }
};

#endif /* _IMP_MAX_CHUNKS_H */
